// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Administrator.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::ceps;

class AdministratorHandler : virtual public AdministratorIf {
 public:
  AdministratorHandler() {
    // Your initialization goes here
  }

  bool connectToPlayer(const ServerAddress& serverAddress) {
    // Your implementation goes here
    printf("connectToPlayer\n");
  }

  bool setPlayerNum(const int16_t num) {
    // Your implementation goes here
    printf("setPlayerNum\n");
  }

  bool setInput(const int32_t value) {
    // Your implementation goes here
    printf("setInput\n");
  }

  bool shareInput() {
    // Your implementation goes here
    printf("shareInput\n");
  }

  bool setPrime(const int32_t prime) {
    // Your implementation goes here
    printf("setPrime\n");
  }

  void evaluateEquation(Answer& _return, const std::vector<std::string> & rpnExpression) {
    // Your implementation goes here
    printf("evaluateEquation\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<AdministratorHandler> handler(new AdministratorHandler());
  shared_ptr<TProcessor> processor(new AdministratorProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

