/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ceps_constants.h"

namespace ceps {

const cepsConstants g_ceps_constants;

cepsConstants::cepsConstants() {
}

} // namespace

