/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ceps_CONSTANTS_H
#define ceps_CONSTANTS_H

#include "ceps_types.h"

namespace ceps {

class cepsConstants {
 public:
  cepsConstants();

};

extern const cepsConstants g_ceps_constants;

} // namespace

#endif
