// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Player.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::ceps;

class PlayerHandler : virtual public PlayerIf {
 public:
  PlayerHandler() {
    // Your initialization goes here
  }

  bool sendOutput(const int16_t pNum, const int32_t value) {
    // Your implementation goes here
    printf("sendOutput\n");
  }

  bool sendInput(const int16_t pNum, const int32_t share) {
    // Your implementation goes here
    printf("sendInput\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<PlayerHandler> handler(new PlayerHandler());
  shared_ptr<TProcessor> processor(new PlayerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

